---
rpa_ipa_titulo:
  texto:
    es: AUTOMATIZACIÓN CON RPA / IPA
    en: RPA / IPA AUTOMATIONS
rpa_ipa1_titulo:
  texto:
    es: RPA es el término utilizado en la industria para las plataformas tecnológicas
      que ayudan a automatizar actividades, imitando el cómo los usuarios interactúan...
    en: RPA is a concept used in the industry to describe computing programs that
      helps users to automate activites by imitating how users interact with systems
      and applicatIons...
rpa_ipa1_link:
  texto:
    es: 'leer más '
    en: 'read more '
chatbot_titulo:
  texto:
    es: CHATBOTS
    en: CHATBOTS
chatbot1_titulo:
  texto:
    es: Te ayudamos con tu estrategia para desarrollar Chatbots conversacionales con
      capacidad de procesamiento de Lenguaje Natural (NLP) complejo ...
    en: We help you with a more complete commercial and customer service strategy,
      using bot that can have conversations with a complex Natural Language Processing
      (NLP)...
chatbot1_link:
  texto:
    es: 'leer más '
    en: 'read more '
tdigital_titulo:
  texto:
    es: TRANSFORMACIÓN DIGITAL
    en: DIGITAL TRANSFORMATION
tdigital1_titulo:
  texto:
    es: Abordamos en conjunto con nuestros clientes los retos de transformación de
      procesos, evaluando las tecnologías que permitirán mejores resultados...
    en: We get onboard with our customers to face challenges on their processes, evaluating
      the best technologies to improve results...
tdigital1_link:
  texto:
    es: 'leer más '
    en: 'read more '
boarding_titulo:
  texto:
    es: ONBOARDING
    en: ONBOARDING
boarding1_titulo:
  texto:
    es: Capacitación de tu equipo interno + acompañamiento para la robotización +
      coaching y creación de tu propio Centro de excelencia...
    en: Training for your internal team + accompaniment in automation + coaching and
      creation of you own Center of excellence...
boarding1_link:
  texto:
    es: 'leer más '
    en: 'read more  '
llave_titulo:
  texto:
    es: PROYECTOS LLAVE EN MANO
    en: KEY IN HAND PROJECTS
llave1_titulo:
  texto:
    es: Nos involucramos en todo el proceso de transformación de nuestros clientes,
      analizando, diseñando y desarrollando las automatizaciones...
    en: We get involved in the whole transformation process of our customers, analyzing,
      designing and developing the automations...
llave1_link:
  texto:
    es: 'leer más '
    en: 'read more '
robot_titulo:
  texto:
    es: ROBOT AS A SERVICE
    en: ROBOT AS A SERVICE
robot1_titulo:
  texto:
    es: Para clientes que no tiene el personal o la infraestructura para una operación
      compleja, pero igualmente se enfrentan a los retos de las actividades...
    en: In order for the customers to face the day to day challenges within a complex
      operation, and have no infrastructure or staff, we can provide a managed service
      to add value...
robot1_link:
  texto:
    es: 'leer más '
    en: 'read more '
anterior_titulo:
  texto:
    es: anterior
    en: previous
siguiente_titulo:
  texto:
    es: siguiente
    en: next
