es:
  rpa_ipa_titulo:
    text: "AUTOMATIZACIONES CON RPA / IPA"
  rpa_ipa1_titulo:
    text: "RPA es el término que usa la industria para 
    programas de cómputo que ayudan a automatizar 
    funciones imitando el como los usuarios interactúan..."
  rpa_ipa1_1_titulo:
    text: "leer más "
  chatbot_titulo:
    text: "CHATBOTS"
  chatbot1_titulo:
    text: "Te ayudamos en la estrategia de desarrollar
    Chatbots conversacionales complejos con capacidad de 
    procesamiento de Lenguaje Natural (NLP)..."
  chatbot1_1_titulo:
    text: "leer más "
  tdigital_titulo:
    text: "TRANSFORMACIÓN DIGITAL"
  tdigital1_titulo:
    text: "Abordamos en conjunto con nuestros clientes 
    los retos de transformación de procesos, evaluando 
    las tecnologías que permitirán mejores resultados..."
  tdigital1_1_titulo:
    text: "leer más "
  boarding_titulo:
    text: "ON BOARDING"
  boarding1_titulo:
    text: "Servicios empaquetados con alcances definidos,
    diseñados para desarrollar las capacidades internas 
    en nuestros clientes y asociados..."
  boarding1_1_titulo:
    text: "leer más "
  llave_titulo:
    tetx: "PROYECTOS LLAVE EN MANO"
  llave1_titulo:
    text: "Nos involucramos en todo el proceso de 
    transformación de nuestros clientes, analizando, 
    diseñando y desarrollando las automatizaciones..."
  llave1_1_titulo:
    text: "leer más "
  robot_titulo:
    text: "ROBOT AS A SERVICE"
  robot1_titulo:
    text: "Para clientes que no tiene el personal o la 
    infraestructura para una operación compleja, pero 
    igualmente se enfrentan a los retos de las 
    actividades..."
  robot1_1_titulo:
    text: "leer más "
  anterior_titulo:
    text: "anterior"
  siguiente_titulo:
    text: "siguiente"

en:
  rpa_ipa_titulo:
    text: "RPA / IPA AUTOMATIONS"
  rpa_ipa1_titulo:
    text: "RPA is a concept used in the industry to 
    describe computing programs that helps users to 
    automate activites by imitating how users interact
    with systems and applicatIons..."
  rpa_ipa1_1_titulo:
    text: "read more "
  chatbot_titulo:
    text: "CHATBOTS"
  chatbot1_titulo:
    text: "We help you with a more complete commercial 
    and customer service strategy, using bot that can 
    have conversations with a Natural Language 
    Processing (NLP)..."
  chatbot1_1_titulo:
    text: "read more "
  tdigital_titulo:
    text: "DIGITAL TRANSFORMATION"
  tdigital1_titulo:
    text: "We get onboard with our customers to face 
    challenges on their processes, evaluating the best 
    technologies to improve results..."
  tdigital1_1_titulo:
    text: "read more "
  boarding_titulo:
    text: "ON BOARDING"
  boarding1_titulo:
    text: "Bundle of services with a defined scope,
    designed to develop internal capabilities within 
    our customers and business partners teams..."
  boarding1_1_titulo:
    text: "read more  "
  llave_titulo:
    text: "KEY IN HAND PROJECTS"
  llave1_titulo:
    text: "We get involved in the whole transformation
    process of our customers, analyzing, designing and 
    developing the automations..."
  llave1_1_titulo:
    text: "read more "
  robot_titulo:
    text: "ROBOT AS A SERVICE"
  robot1_titulo:
    text: "In order for the customers to face the day 
    to day challenges within a complex operation, and 
    have no infrastructure or staff, we can provide a 
    managed service to add value..."
  robot1_1_titulo:
    text: "read more "
  anterior_titulo:
    text: "previous"
  siguiente_titulo:
    text: "next"
  